name: Parent Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      example_input: 'sebastian'
    secrets:
      SOME_SECRET: ${{ secrets.SOME_SECRET }}