name: Parent Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/workflow-hijo.yaml
    with:
      example_input: 'sebastian'
    secrets:
      test-secret: ${{ secrets.SOME_SECRET }}