name: Parent Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  llamada-a-workflow-hijo:
    name: Call Child Workflow
    uses: benzal-test/workflow-hijo/.github/workflows/workflow-hijo-fuera.yaml@main
    with:
      example_input: 'sebastian'
    secrets:
      test-secret: ${{ secrets.SOME_SECRET }}